version: "3"
services:
  laravel-t-shirts-db:
    image: mariadb:latest
    container_name: laravel-t-shirts-db
    volumes:
      - "/home/valentin/Internship_Development-Aid/My_Application/application/laravel-t-shirts/docker-containers/db:/var/lib/mysql"
      - "/home/valentin/Internship_Development-Aid/My_Application/application/laravel-t-shirts/docker-compose/database/config:/etc/mysql/conf.d"
    ports:
      - "33066:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel_t_shirts_network
    restart: unless-stopped

  laravel-t-shirts-app:
    image: amoraresco/it-academy-project:latest
    container_name: laravel-t-shirts-app
    links:
      - laravel-t-shirts-db
    ports:
      - "88:80"
      - "8822:22"
    volumes:
      - "/home/valentin/Internship_Development-Aid/My_Application/application/laravel-t-shirts:/var/www/html"
    environment:
      - APP_URL=http://localhost
      - MAIL_HOST=mailhog
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ENCRYPTION=null
      - MAIL_PORT=1025
      - MAIL_FROM_ADDRESS=info@t-shirts.com
      - MAIL_NAME="T-shirts"
      - MAIL_DELAY=2500
      - DB_HOST=laravel-t-shirts-db
      - DB_DATABASE=laravel_t_shirts_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306
    networks:
      - laravel_t_shirts_network
    restart: unless-stopped

  laravel-t-shirts-mailhog:
    image: mailhog/mailhog
    container_name: laravel-t-shirts-mailhog
    ports:
      - "8025:8025"
    networks:
      - laravel_t_shirts_network

networks:
  laravel_t_shirts_network:
    driver: bridge